excluded:
  - vendor
  - Pods
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - file_header
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  MovieDatabase.*
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2,4}\.
                    \/\/  Copyright © \d{4} Oleksii Kalentiev\. All rights reserved\.
                    \/\/
line_length: 160
number_separator:
  minimum_length: 5

custom_rules:
  unit_test_name:
    included: '.*(Unit|[^UI])Test(s|).swift'
    name: "Unit test name" 
    regex: '(func test(([a-zA-Z0-9]+)|([a-zA-Z0-9]+_((?!with).)*)|([a-zA-Z0-9]+_[a-zA-Z0-9]+_((?!should).)*))\(\).*)' 
    message: "Unit test name format is incorrect"  
    severity: warning 